---
- name: "deployment play." 
  hosts: web
  remote_user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_host_key_checking: false
    ansible_stdout_callback: yaml

  environment:
    NODE_ENV: production
    VERSION: 1
    TYPEORM_CONNECTION: postgres # "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR: ./src/migrations # "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR') }}"
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity{.ts,.js} # "{{ lookup('env', 'TYPEORM_ENTITIES') }}"
    TYPEORM_MIGRATIONS: ./src/migrations/*.ts  # "{{ lookup('env', 'TYPEORM_MIGRATIONS') }}"
    TYPEORM_HOST: udapeople-prod.cjckrotun9g5.us-east-1.rds.amazonaws.com # "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: 5432  # "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: postgres # "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: udapeopledbpassw0rd # "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: postgres # "{{ lookup('env', 'TYPEORM_DATABASE') }}"
    
  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 600

    - name: "install python for Ansible."
      become: true
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false
    
    - setup:

  roles:
    - deploy